title: "Vanessa D’Amario"
description: "AI × Healthcare · Global Health · Trustworthy ML"
url: "https://vanessadamario.github.io"
theme: minima
author:
  name: "Vanessa D’Amario"
  email: "vdamario@nova.edu"
  avatar: "/assets/img/vanessa.png"

# Easy-to-edit profile links (fill these in once and the site updates everywhere)
profile_links:
  cv: "/cv.pdf"                           # add cv.pdf at repo root when ready
  scholar: "https://scholar.google.com/citations?user=vFwd8YoAAAAJ&hl=en/"  # replace with your Scholar profile link
  github: "https://github.com/vanessadamario"
  linkedin: "https://www.linkedin.com/in/vanessa-d-amario-81b0b1184/"   # replace with your LinkedIn
  email: "mailto:vdamario@nova.edu"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Minima theme settings
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/vanessadamario" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/vanessa-d-amario-81b0b1184/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=vFwd8YoAAAAJ&hl=en/" }
show_excerpts: false
